### ISSUE TITLE
required attribute

### ISSUE THREAD

**Issue by fahdrahali** [Regiss05/Awesome-Books#2]
**You have made an excellent Javascript implementation to your code**. when you click on the button submit and the filed input text is empty, you added an empty object,  kindly you should add the required attribute to the field input text

**Comment by EzekielUtshudi** [comment]
Great work Cedrick, keep it up, always remember to update your readMe file to fit the current project, but this was clean codes,
happy coding.

**Comment by kosher9** [comment]
Thank you, guys.
