### ISSUE TITLE
## Webhint analyse  error 

### ISSUE THREAD

**Issue by DanUshindi** [Regiss05/Awesome-Books#6]
Congratulation,
You made a great job, I wish you to continue like that but you still have a problem to fix with web hint linters

**Comment by kosher9** [comment]
Thank you for your feedback. I have finally found a solution to this issue. you can check it [here](https://questions.microverse.org/t/webhint-report-cannot-read-property-getlocation-of-undefined/2518/4)

**Comment by EzekielUtshudi** [comment]
Great, work.
